CONTENT_TYPE = "audio/wav"
WORD_ALTERNATIVE_THRESHOLDS = 0.9
KEYWORDS = ["hey", "hi", "watson", "friend", "meet"]
KEYWORDS_THRESHOLD = 0.5
GPT_MODEL = "gpt-4"
MAX_TOKENS = 1000
TEMPERATURE = 1.2
AUDIO_FORMAT = "audio/wav"
VOICE = "en-US_AllisonV3Voice"
